suorganizer/blog/urls.py
from django.conf.urls import url

from .views import (
    PostCreate, PostList, PostUpdate,
    PostDelete, PostArchiveYear, PostArchiveMonth,
    PostDetail)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),

]

suorganizer/suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView


from blog import urls as blog_urls
from contact import urls as contact_urls
from organizer.urls import (
    startup as startup_urls,
    tag as tag_urls)
from user import urls as user_urls


admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'

urlpatterns = [
    
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^$', RedirectView.as_view(
            pattern_name='blog_post_list',
            permanent=False)),
    url(r'^user/', include(
                        user_urls,
                        app_name='user',
                        namespace='dj-auth')),
    
]

suorganizer/user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView, TemplateView
from django.core.urlresolvers import reverse_lazy

from .views import (
    DisableAccout, ActivateAccount, CreateAccount,
    ResendActivationEmail, ProfileDetail, ProfileUpdate,
    PublicProfileDetail)


password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),

    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect':reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),

    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
         name='pw_reset_start'),

    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),

    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect':reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
            {'form':AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^disable/$',
        DisableAccout.as_view(),
        name='disable'),

    url(r'^login/$',
        auth_views.login,
        {'template_name':'user/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name':'user/logged_out.html',
         'extra_context':
                {'form':AuthenticationForm}},
        name='logout'),

    url(r'^password/', include(password_urls)),

    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),

    url(r'^create/$',CreateAccount.as_view(),name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(template_name='user/user_create_done.html'),
        name='create_done'),

    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name='profile_update'),
    url(r'(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),
]

suorganizer/user/models.py
from datetime import date

from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    slug = models.SlugField(max_length=30, unique=True)
    about = models.TextField()
    name = models.CharField(max_length=255)
    joined = models.DateTimeField("Date Joined", auto_now_add=True)

    def __str__(self):
        return self.user.get_username()

    def get_update_url(self):
        return reverse('dj-auth:profile_update')

    def get_absolute_url(self):
        return reverse(
            'dj-auth:public_profile',
            kwargs={'slug':self.slug})


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **kwargs):
        email = self.normalize_email(email)
        is_staff = kwargs.pop('is_staff',False)
        is_superuser = kwargs.pop('is_superuser', False)
        user = self.model(
            email=email,
            is_active=True,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None,**extra_fields):
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, is_staff=True, 
            is_superuser=True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        'email address',
        max_length=254,
        unique=True)
    is_staff = models.BooleanField(
        'staff status',
        default=False,
        help_text=(
            'Designates whether the user can '
            'log into this admin site.'))
    is_active = models.BooleanField(
        'active',
        default=True,
        help_text=(
            'Designates whether this user should '
            'be treated as active. Unselect this '
            'instead of deleting accounts.'))
    objects = UserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return self.profile.get_absolute_url()

    def get_full_name(self):
        return self.profile.name

    def get_short_name(self):
        return self.profile.name

    def published_posts(self):
        return self.blog_posts.filter(pub_date__lt=date.today)

suorganizer/user/forms.py
import logging

from django import forms
from django.contrib.auth.forms import (
    UserChangeForm as BaseUserChangeForm,
    UserCreationForm as BaseUserCreationForm)
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .models import Profile
from .utils import ActivationMailFormMixin


logger = logging.getLogger(__name__)


class ResendActivationEmailForm(ActivationMailFormMixin, forms.Form):

    email = forms.EmailField()

    mail_validation_error = (
        'Could not re-send activation email. '
        'Please try again later. (Sorry!)')

    def save(self, **kwargs):
        User = get_user_model()
        try:
            user = User.objects.get(email=self.cleaned_data['email'])
        except:
            logger.warning(
                'Resend Activation: No user with '
                'email: {} .'.format(
                    self.cleaned_data['email']))
            return None
        self.send_mail(user=user, **kwargs)
        return user


class UserCreationForm(
        ActivationMailFormMixin,
        BaseUserCreationForm):
    
    name = forms.CharField(
        max_length=255,
        help_text=(
            "The name displayed on your public profile."))

    mail_validation_error = (
        'User created. Could not send activation '
        'email. Please try again later. (Sorry!)')


    class Meta(BaseUserCreationForm.Meta):
        model = get_user_model()
        fields = ('name', 'email')

    def save(self, **kwargs):
        user = super().save(commit=False)
        if not user.pk:
            user.is_active = False
            send_mail = True
        else:
            send_mail = False
        user.save()
        self.save_m2m()
        Profile.objects.update_or_create(
            user=user,
            defaults={
                'name':self.cleaned_data['name'],
                'slug':slugify(
                    self.cleaned_data['name']),
            })
        if send_mail:
            self.send_mail(user=user, **kwargs)
        return user

    def clean_name(self):
        name = self.cleaned_data['name']
        disallowed = (
            'activate',
            'create',
            'disable',
            'login',
            'logout',
            'password',
            'profile',
        )
        if name in disallowed:
            raise ValidationError(
                "A user with that name already exists.")
        return name


class UserChangeForm(BaseUserChangeForm):

    class Meta(BaseUserChangeForm.Meta):
        model = get_user_model()

suorganizer/user/views.py
from django.conf import settings
from django.contrib.auth import get_user, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import \
    default_token_generator as token_generator
from django.contrib.messages import error, success
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.views.generic import View, DetailView
from django.core.urlresolvers import reverse_lazy
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from .forms import UserCreationForm, ResendActivationEmailForm
from .utils import MailContextViewMixin, ProfileGetObjectMixin
from .decorators import class_login_required
from .models import Profile

from core.utils import UpdateView



class DisableAccout(View):
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = (
        'user/user_confirm_delete.html')

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self, request):
        return TemplateResponse(request, self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self, request):
        user = get_user(request)
        user.set_unusable_password()
        user.is_active = False
        user.save()
        logout(request)
        return redirect(self.success_url)


class CreateAccount(MailContextViewMixin, View):
    form_class = UserCreationForm
    success_url = reverse_lazy('dj-auth:create_done')
    template_name = 'user/user_create.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form':self.form_class()})

    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters('password1','password2'))
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save(**self.get_save_kwargs(request))
            if bound_form.mail_sent:
                return redirect(self.success_url)
            else:
                errs = bound_form.non_field_errors()
                for err in errs:
                    error(request, err)
                return redirect('dj-auth:resend_activation')
        return TemplateResponse(
            request, self.template_name,
            {'form':bound_form})


class ActivateAccount(View):
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'user/user_activate.html'

    @method_decorator(never_cache)
    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if (user is not None and token_generator.check_token(user, token)):
            user.is_active = True
            user.save()
            success(request,'UserActivated! You may now login.')
            return redirect(self.success_url)
        else:
            return TemplateResponse(request, self.template_name)


class ResendActivationEmail(MailContextViewMixin, View):
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'user/resend_activation.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request, 
            self.template_name,
            {'form':self.form_class()})

    @method_decorator(csrf_protect)
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            user = bound_form.save(**self.get_save_kwargs(request))
            if (user is not None 
                    and not bound_form.mail_sent):
                errs = bound_form.non_field_errors()
                for err in errs:
                    error(request, err)
                if errs:
                    bound_form.errors.pop('__all__')
                return TemplateResponse(
                    request,
                    self.template_name,
                    {'form':bound_form})
        success(request, 'Activation Email Sent!')
        return redirect(self.success_url)


@class_login_required
class ProfileDetail(ProfileGetObjectMixin, DetailView):
    model = Profile


@class_login_required
class ProfileUpdate(ProfileGetObjectMixin, UpdateView):
    fields = ('about',)
    model = Profile


class PublicProfileDetail(DetailView):
    model = Profile

suorganizer/user/templates/user/base_user.html
{% extends parent_template|default:"base.html" %}

suorganizer/user/templates/user/logged_out.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Logged Out
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <p>You've successfully logged out.</p>
            {% include "user/login_form.html" 
                with login_button='Log Back'%}
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/login.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Login
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two five columns">
            {% include "user/login_form.html" %}
        </div>
        <div class="three columns">
            <ul class="task-list">
                <li>
                    <a href="{% url 'dj-auth:create' %}">
                        Register New Account
                    </a>
                </li>
                <li>
                    <a href="{% url 'dj-auth:resend_activation' %}">
                        Lost Activation E-Mail?
                    </a>
                </li>
                <li>
                    <a href="{% url 'dj-auth:pw_reset_start' %}">
                        Forgotten password?
                    </a>
                </li>

            </ul>
        </div>
    </div>

{% endblock content %}

suorganizer/user/templates/user/login_form.html
<form
    action="{% url 'dj-auth:login' %}"
    method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if next %}
        <input type="hidden" name="next" value="{{ next }}">
    {% endif %}
    <button type="submit">
        {{ login_button|default:'Log in'}}
    </button>
</form>

suorganizer/user/templates/user/password_change_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Change Password
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <p>Password successfully changed.</p>
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/password_change_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Change Password
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <form
                action="{% url 'dj-auth:pw_change' %}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Change Password</button>
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/password_reset_confirm.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Reset Password
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            {% if validlink %}
                <p>Enter a new password below.</p>
                <form
                    action="{{ request.path }}"
                    method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button
                        class="button-primary"
                        type="submit">
                        Save New Password
                    </button>
                </form>
            {% else %}
                <p>This reset link is no longer valid.</p>
                <p>
                    Please request a new reset email
                    <a href="{% url 'dj-auth:pw_reset_start' %}">here</a>.
                </p>

            {% endif %}
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/password_reset_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Reset Password
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <div class="center">
                <p>Reset your password by email.</p>
            </div>
            <form
                action="{% url 'dj-auth:pw_reset_start' %}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                    Send Me Reset Instructions
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/password_reset_sent.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Password Reset Sent
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <p>Password reset email sent!</p>
            <p>Please check your inbox and spam box.</p>
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/profile_detail.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - {{ profile.user.get_full_name }}'s Profile
{% endblock title %}

{% block content %}
    <div class="row">
        {% if user.pk == profile.user.pk %}
            <div class="offset-by-two five columns">
        {% else %}
            <div class="offset-by-two eight columns">
        {% endif %}
            <h2>About {{ profile.user.get_full_name }}</h2>
            {{ profile.about|default:"No Profile"|linebreaks }}
        </div>
        {% if user.pk == profile.user.pk %}
        <div class="three columns">
            {% if perms.blog.view_future_post and profile.user.blog_posts.all %}
            <section>
                <h3>Blog Post {{ profile.user.blog_posts|pluralize }}</h3>
                <ul>
                    {% for post in profile.user.blog_posts %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.title|title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
            {% else profile.user.published_posts|length > 0 %}
            <section>
                <h3>Blog Post {{ profile.user.published_posts|pluralize }}</h3>
                <ul>
                    {% for post in profile.user.published_posts %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.title|title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
            {% endif %}
            <ul class="task-list">
                <li>
                    <a href="{% url 'dj-auth:pw_change' %}">
                        Change Password
                    </a>
                </li>
                <li>
                    <a href="{{ profile.get_update_url }}">
                        Edit Your Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'dj-auth:disable' %}">
                        Disable Account
                    </a>
                </li>
            </ul>
        </div>
        {% endif %}
    </div>
{% endblock content %}

suorganizer/user/templates/user/profile_form_update.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Update Profile
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <form
                action="{{ profile.get_update_url }}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Profile</button>
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/user_activate.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Account Activation Failed
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <p>This actication link is no longer valid.</p>
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/user_create.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Create Account
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <div class="center">
                <a href="{% url 'dj-auth:resend_activation' %}">
                    Lost Activation E-Mail?
                </a>
            </div>
            <form
                action="{% url 'dj-auth:create' %}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create New Account</button>
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/user/templates/user/user_create_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Account Created
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <p>Your account has been created!</p>
            <p>Please check your email for the activation link.</p>
        </div>
    </div>
{% endblock content %}