suorganizer/blog/urls.py
from django.conf.urls import url

from .views import (
    PostCreate, PostList, PostUpdate,
    PostDelete, PostArchiveYear, PostArchiveMonth,
    PostDetail)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),

]

suorganizer/suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView


from blog import urls as blog_urls
from contact import urls as contact_urls
from organizer.urls import (
    startup as startup_urls,
    tag as tag_urls)
from user import urls as user_urls


admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'

urlpatterns = [
    
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^$', RedirectView.as_view(
            pattern_name='blog_post_list',
            permanent=False)),
    url(r'^user/', include(
                        user_urls,
                        app_name='user',
                        namespace='dj-auth')),
    
]

suorganizer/blog/models.py
from datetime import date
from django.db import models
from organizer.models import Startup, Tag
from django.core.urlresolvers import reverse
from django.conf import settings


class PostQueryset(models.QuerySet):

    def published(self):
        return self.filer(pub_date__lte=date.today())


# class PostManager(models.Manager):

#     def get_queryset(self):
#         return PostQueryset(self.model, using=self._db)

#     def published(self):
#         return self.get_queryset().published()

class BasePostManager(models.Manager):

    def get_by_natural_key(self,pub_date,slug):
        return self.get(pub_date=pub_date, slug=slug)

PostManager = BasePostManager.from_queryset(PostQueryset)

class Post(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63,
                            help_text='A label for URL config',
                            unique_for_month='pub_date')
    text = models.TextField()
    pub_date = models.DateField('date published',
                                auto_now_add=True)
    tags = models.ManyToManyField(Tag,related_name='blog_posts', blank=True)
    startups = models.ManyToManyField(Startup, blank=True, related_name='blog_posts')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_posts')
    objects = PostManager()

    class Meta:
        verbose_name='blog post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'
        permissions = (
            ("view_future_post",
             "Can view unpublished Post"),
        )
    
    def __str__(self):
        return "{} on {}".format(
            self.title,
            self.pub_date.strftime('%Y-%m-%d'))

    def get_absolute_url(self):
        return reverse(
            'blog_post_detail',
            kwargs={'year':self.pub_date.year,
                    'month':self.pub_date.pub_date.month,
                    'slug':self.slug})

    def get_update_url(self):
        return reverse(
            'blog_post_update',
            kwargs={'year': self.pub_date.year,
                    'month': self.pub_date.month,
                    'slug': self.slug})

    def get_delete_url(self):
        return reverse(
            'blog_post_delete',
            kwargs={'year':self.pub_date.year,
                    'month':self.pub_date.month,
                    'slug':self.slug})

    def get_archive_year_url(self):
        return reverse(
            'blog_post_archive_year',
            kwargs={'year':self.pub_date.year})

    def get_archive_month_url(self):
        return reverse(
            'blog_post_archive_month',
            kwargs={'year':self.pub_date.year,
                    'month':self.pub_date.month})

    @property
    def tag_count(self):
        return self.tags.count()

    def natural_key(self):
        return (self.pub_date, self.slug)
    natural_key.dependencies = [
        'organizer.startup',
        'organizer.tag',
        'user.user',
    ]




































        

suorganizer/blog/forms.py
from django import forms
from django.contrib.auth import get_user

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('author',)

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

    def save(self, request, commit=True):
        post = super().save(commit=False)
        if not post.pk:
            post.author = get_user(request)
        if commit:
            post.save()
            self.save_m2m()
        return post
        

suorganizer/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (
    View, CreateView, ListView, YearArchiveView,
    MonthArchiveView, ArchiveIndexView, DeleteView,
    DetailView)
from django.views.decorators.http import require_http_methods
from django.core.urlresolvers import reverse_lazy

from .models import Post
from .forms import PostForm
from .utils import (
    PostGetMixin, DateObjectMixin, AllowFuturePermissionMixin, 
    PostFormValidMixin)
from user.decorators import require_authenticated_permission


from core.utils import UpdateView


class PostDetail(DateObjectMixin, DetailView):
    
    date_field = 'pub_date'
    model = Post

class PostArchiveYear(YearArchiveView):
    model = Post
    date_field = 'pub_date'
    make_object_list = True


class PostArchiveMonth(MonthArchiveView):
    model = Post
    date_field = 'pub_date'
    month_format = '%m'


class PostList(
        AllowFuturePermissionMixin,
        ArchiveIndexView):
    allow_empty = True
    context_object_name = 'post_list'
    date_field = 'pub_date'
    make_object_list = True
    model = Post
    paginate_by = 5
    template_name = 'blog/post_list.html'


@require_authenticated_permission('blog.add_post')
class PostCreate(PostFormValidMixin, CreateView):
    form_class = PostForm
    model = Post


class PostUpdate(PostFormValidMixin, DateObjectMixin, UpdateView):
    date_field = 'pub_date'
    form_class = PostForm
    model = Post

class PostDelete(DateObjectMixin, DeleteView):
    date_field = 'pub_date'
    model = Post
    success_url = reverse_lazy('blog_post_list')

suorganizer/organizer/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import (
    View, DetailView, CreateView, 
    DeleteView, ListView, DateDetailView)
from django.core.paginator import (
    EmptyPage, PageNotAnInteger, Paginator)
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import (
    login_required, 
    user_passes_test,
    permission_required)
from django.utils.decorators import method_decorator
from django.contrib.auth import PermissionDenied



from .models import Tag, Startup, NewsLink
from .forms import (
    TagForm, StartupForm, NewsLinkForm)
from .utils import (
    CreateView, ObjectUpdateMixin, ObjectDeleteMixin,
    PageLinksMixin,NewsLinkGetObjectMixin, StartupContextMixin)
from user.decorators import require_authenticated_permission, class_login_required

from core.utils import UpdateView


class TagList(PageLinksMixin, ListView):
    paginate_by = 5
    model = Tag


class StartupList(PageLinksMixin, ListView):
    model = Startup
    paginate_by = 5


class NewsLinkCreate(
                     NewsLinkGetObjectMixin,
                     StartupContextMixin,
                     CreateView):
    form_class = NewsLinkForm
    model = NewsLink

    def get_initial(self):
        startup_slug = self.kwargs.get(
            self.startup_slug_url_kwarg)
        self.startup = get_object_or_404(
            Startup, slug__iexact=startup_slug)
        initial = {
            self.startup_context_object_name:
                self.startup,
        }
        initial.update(self.initial)
        return initial


class StartupCreate(CreateView):
    form_class = StartupForm
    model = Startup
    template_name = 'organizer/startup_form.html'


def in_contrib_group(user):
    if user.groups.filter(name='contributors'):
        return True
    else:
        raise PermissionDenied


@require_authenticated_permission('organizer.add_tag')
class TagCreate(CreateView):
    form_class = TagForm
    model = Tag
    template_name = 'organizer/tag_form.html'

    


class NewsLinkUpdate(
        NewsLinkGetObjectMixin,
        StartupContextMixin,
        UpdateView):
    form_class = NewsLinkForm
    model = NewsLink
    slug_url_kwarg = 'newslink_slug'


@require_authenticated_permission('organizer.change_tag')
class TagUpdate(UpdateView):
    form_class = TagForm
    model = Tag


@require_authenticated_permission('organizer.change_startup')
class StartupUpdate(UpdateView):
    form_class = StartupForm
    model = Startup


class NewsLinkDelete(StartupContextMixin,DeleteView):
    model = NewsLink
    slug_url_kwarg = 'newslink_slug'


class TagDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy('organizer_tag_list')


class StartupDelete(DeleteView):
    model = Startup
    success_url = reverse_lazy('organizer_startup_list')
    


class TagPageList(View):
    paginate_by = 5
    template_name = 'organizer/tag_list.html'

    def get(self, request, page_number):
        tags = Tag.objects.all()
        paginator = Paginator(
            tags, self.paginate_by)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(
                paginator.num_pages)

        if page.has_previous():
            prev_url = reverse(
                'organizer_tag_page',
                args=(
                    page.previous_page_number(),
                ))
        else:
            prev_url = None
        if page.has_next():
            next_url = reverse(
                'organizer_tag_page',
                args=(
                    page.next_page_number(),
                ))
        else:
            next_url = None

        context = {
            'is_paginated':
                page.has_other_pages(),
            'next_page_url': next_url,
            'paginator':paginator,
            'previous_page_url': prev_url,
            'tag_list':page,
        }
        return render(
            request, self.template_name, context)


class TagDetail(DetailView):

    context_object_name = 'tag'
    model = Tag
    template_name = 'organizer/tag_detail.html'

class StartupDetail(DetailView):

    context_object_name = 'startup'
    model = Startup
    template_name = 'organizer/startup_detail.html'

suorganizer/blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

{% load staticfiles %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
{% endblock head %}

suorganizer/blog/templates/blog/post_archive_month.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - {{ month|date:"F Y" }} Posts
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="eight columns">
            <div class="mobile">
                <a href="{% url 'blog_post_create' %}"
                   class="button button-primary">
                    Write New Blog Post
                </a>
            </div>
        </div>
        <div class="desktop four columns">
            <a href="{% url 'blog_post_create' %}"
               class="button button-primary">
                Write New Blog Post
            </a>
            <h2>All Posts for {{ month|date:"F Y" }}</h2>
            {% for post in post_list %}
                <article class="list-item">
                    <header>
                        <h3>
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.title|title }}
                            </a>
                        </h3>
                        <p>
                            Written on:
                            <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                                {{ post.pub_date|date:'1, F j, Y' }}
                            </time>
                        </p>
                    </header>
                    <ul class="inline">
                        <li>
                            <a href="{{ post.get_update_url }}"
                               class="button">
                                Edit Post
                            </a>
                        </li>
                        <li>
                            <a href="{{ post.get_delete_url }}"
                               class="button">
                                Delete Post
                            </a>
                        </li>
                    </ul>
                    <p>
                        {{ post.text|truncatewords:20 }}
                    </p>
                    <p class="read-more">
                        <a href="{{ post.get_absolute_url }}">
                            Read more...
                        </a>
                    </p>
                </article>
            {% endfor %}
            <p>
                <a href="{% url 'blog_post_archive_year' month|date:'Y' %}">
                    All Posts from {{ month|date:"Y" }}
                </a>
            </p>
            <p>
                <a href="{% url 'blog_post_list' %}">
                    Latest Posts
                </a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="twelve columns">
            <ul class="pagination">
                {% if previous_month %}
                    <li>
                        <a href="{% url 'blog_post_archive_month'
                                         previous_month|date:'Y'
                                         previous_month|date:'m'%}">
                            Posts from {{ previous_month|date:'F Y' }}                      
                        </a>
                    </li>
                {% endif %}
                {% if next_month %}
                    <li>
                        <a href="{% url 'blog_post_archive_month'
                                        next_month|date:'Y' 
                                        next_month|date:'m' %}">
                            Posts from {{ next_month|date:'F Y' }}     
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>    
    </div>
{% endblock content %}

suorganizer/blog/templates/blog/post_archive_year.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - {{ year|date:"Y" }}
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="desktop four columns">
            <h3>Archives by Month</h3>
            <div class="eight columns">
                <div class="mobile">
                    <a href="{% url 'blog_post_create' %}"
                       class="button button-primary">
                        Write New Blog Post
                    </a>
                </div>
                <ul>
                    {% for m in date_list %}
                        <li>
                            <a href="">
                                {{ m|date:"F Y" }}
                            </a>
                            <h2>All Posts for {{ year|date:"Y" }}</h2>
                            {% for post in post_list %}
                                <article class="list-item">
                                    <header>
                                        <h3>
                                            <a href="{{ post.get_absolute_url }}">
                                                {{ post.title|title }}
                                            </a>
                                        </h3>
                                        <ul class="inline">
                                            <li>
                                                <a href="{{ post.get_update_url }}"
                                                   class="button">
                                                    Edit Post
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{{ post.get_delete_url }}"
                                                   class="button">
                                                    Delete Post
                                                </a>
                                            </li>
                                        </ul>
                                        <p>
                                            Written on:
                                            <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                                                {{ post.pub_date|date:"1, F j, Y" }}
                                            </time>
                                        </p>
                                    </header>
                                    <a href="{% url 'blog_post_create' %}"
                                       class="button button-primary">
                                        Write New Blog Post
                                    </a>
                                    <p>
                                        {{ post.text|truncatewords:20 }}
                                    </p>
                                    <p class="read-more">
                                        <a href="{{ post.get_absolute_url }}">
                                            Read more&hellip;
                                        </a>
                                    </p>
                                </article>
                            {% endfor %}
                        </li>
                        <li>
                            <a href="{% url 'blog_post_archive_month' 
                               m|date:'Y' m|date:'n' %}">
                                {{ m|date:'F Y' }}
                            </a>
                        </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="twelve columns">
            <ul class="pagination">
                {% if previous_year %}
                    <li>
                        <a href="{% url 'blog_post_archive_year' 
                                        previous_year|date:'Y' %}">
                            Posts from {{ previous_year|date:"Y" }}
                        </a>
                    </li>
                {% endif %}
                {% if next_year %}
                    <li>
                        <a href="{% url 'blog_post_archive_year' 
                                        next_year|date:'Y' %}">
                            Posts from {{ next_year|date:"Y" }}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock content %}

suorganizer/blog/templates/blog/post_detail.html
{% extends parent_template|default:"blog/base_blog.html" %}
{% block title %}
    {{ block.super }} - {{ post.title|title }}
{% endblock title %}
{% block content %}
    <article>
        <header>
            <h2>{{ post.title|title }}</h2>
            <p>
                Written on
                <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                    {{ post.pub_date|date:"1, F j, Y"}}
                </time>
            </p>
            <ul>
                <li>
                    <a href="{{ post.get_update_url }}">
                        Edit Post
                    </a>
                </li>
                <li>
                    <a href="{{ post.get_delete_url }}">
                        Delete Post
                    </a>
                </li>
            </ul>
        </header>
        
        {{ post.text|linebreaks }}

        {% if post.startups.all or post.tags.all %}
            <footer>

                {% if post.startups.all %}
                    <section>
                        <h3>Startup{{ post.startups.count|pluralize }}</h3>
                        <ul>
                            {% for startup in post.startups.all %}
                                <li>
                                    <a href="{{ startup.get_absolute_url }}">
                                        {{ startup.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </section>
                {% endif %}

                {% if post.tags.all %}
                    <section>
                        <h3>Tag{{ post.tags.count|pluralize }}</h3>
                        <ul>
                            {% for tag in post.tags.all %}
                                <li>
                                    <a href="{{ tag.get_absolute_url }}">
                                        {{ tag.name|title }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </section>
                {% endif %}
            </footer>
        {% endif %}
    
    </article>
{% endblock content %}

suorganizer/blog/templates/blog/post_form.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - Create Blog Post
{% endblock title %}

{% block content %}
    <div>
        <div>
            <form action="{% url 'blog_post_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Blog Post</button>
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/blog/templates/blog/post_list.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - Blog
{% endblock title %}

{% block content %}
<div class="row">
    <div class="eight columns">
    {% if perms.blog.add_post %}
        <div class="mobile">
          <a
              href="{% url 'blog_post_create' %}"
              class="button button-primary">
            Write New Blog Post</a>
        </div>
    {% endif %}
    {% for post in post_list %}
        <article>
            <header>
                <h2>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title|title }}
                    </a>
                </h2>
                {% if perms.blog.change_post or perms.blog.delete_post %}
                  <ul class="inline">
                    {% if perms.blog.change_post %}
                      <li>
                        <a
                            href="{{ post.get_update_url }}"
                            class="button">
                          Edit Post</a></li>
                    {% endif %}
                    {% if perms.blog.delete_post %}
                      <li>
                        <a
                            href="{{ post.get_delete_url }}"
                            class="button">
                          Delete Post</a></li>
                    {% endif %}
                  </ul>
                {% endif %}
                <p>
                    Written on:
                    <time datetime="{{ post.pub_date|date:'Y-m-d' }}">
                        {{ post.pub_date|date:"1, F j, Y" }}
                    </time>
                </p>
            </header>
            <p>{{ post.text|truncatewords:20 }}</p>
            <p class="read-more">
                <a href="{{ post.get_absolute_url }}">
                    Read more&hellip;
                </a>
            </p>
        </article>
    {% empty %}
        <p class="center"><em>No Blog Posts Available</em></p>
    {% endfor %}
    </div>
    <div class="desktop four columns">
        {% if perms.blog.add_post %}
            <a
              href="{% url 'blog_post_create' %}"
              class="button button-primary">
            Write New Blog Post</a>
          {% endif %}
        <h3>Post Archives</h3>
        <ul>
            {% for y in date_list %}
                <li>
                    <a href="{% url 'blog_post_archive_year' y|date:'Y' %}">
                        {{ y|date:'Y' }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}