suorganizer/blog/urls.py
from django.conf.urls import url

from .views import (
    PostCreate, PostList, PostUpdate,
    PostDelete, PostArchiveYear, PostArchiveMonth,
    PostDetail)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),

]

suorganizer/suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView


from blog import urls as blog_urls
from contact import urls as contact_urls
from organizer.urls import (
    startup as startup_urls,
    tag as tag_urls)
from user import urls as user_urls


admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'

urlpatterns = [
    
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^$', RedirectView.as_view(
            pattern_name='blog_post_list',
            permanent=False)),
    url(r'^user/', include(
                        user_urls,
                        app_name='user',
                        namespace='dj-auth')),
    
]

suorganizer/user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView, TemplateView
from django.core.urlresolvers import reverse_lazy

from .views import (
    DisableAccout, ActivateAccount, CreateAccount,
    ResendActivationEmail, ProfileDetail, ProfileUpdate,
    PublicProfileDetail)


password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),

    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect':reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),

    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
         name='pw_reset_start'),

    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),

    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect':reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
            {'form':AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^disable/$',
        DisableAccout.as_view(),
        name='disable'),

    url(r'^login/$',
        auth_views.login,
        {'template_name':'user/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name':'user/logged_out.html',
         'extra_context':
                {'form':AuthenticationForm}},
        name='logout'),

    url(r'^password/', include(password_urls)),

    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),

    url(r'^create/$',CreateAccount.as_view(),name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(template_name='user/user_create_done.html'),
        name='create_done'),

    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name='profile_update'),
    url(r'(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),
]

suorganizer/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            Startup Organizer
        {% endblock title %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'site/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'site/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}">
    {% block head %}
        
    {% endblock head %}
</head>
<body>
    <div class="container">
        <div class="status row">
            <div class="offset-by-eight four columns">
                <ul class="inline">
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'dj-auth:profile' %}">
                        View Profile</a></li>
                      <li><a href="{% url 'dj-auth:logout' %}?next={{ request.path }}">
                        Log Out</a></li>
                    {% else %}
                      <li><a href="{% url 'dj-auth:create' %}">
                        Register</a></li>
                      <li><a href="{% url 'dj-auth:login' %}?next={{ request.path }}">
                        Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <header class="row">
            <div class="offset-by-one ten columns">
                <h1 class="logo">Startup Organizer</h1>
            </div>
        </header>
        <nav>
            <ul>
              <li>
                <a href="{% url 'about_site' %}">
                  About</a></li>
              <li>
                <a href="{% url 'blog_post_list' %}">
                  Blog</a></li>
              <li>
                <a href="{% url 'organizer_startup_list' %}">
                  Startups</a></li>
              <li>
                <a href="{% url 'organizer_tag_list' %}">
                  Tags</a></li>
              <li>
                <a href="{% url 'contact' %}">
                  Contact</a></li>
            </ul>
        </nav>
    </div>
    
    {% if messages %}
        <div class="row">
            <div class="twelve columns">
                <ul class="messages">
                    {% for message in message %}
                        {% if message.tags %}
                            <li class="{{ message.tags }}">
                        {% else %}
                            <li>
                        {% endif %}
                        {{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
    <main >
        {% block content %}
            This is default content!
        {% endblock content %}
    </main>

    <footer>
        <p>
            &copy; 2015
            <a href="https://AndrewsForge.com/">
                Andrew Pinkham
            </a>
        </p>
        <p>
            Created for
            <a href="https://Django-Unleashed.com/">
                Django Unleashed
            </a>
        </p>
    </footer>
</body>
</html>