suorganizer/blog/urls.py
from django.conf.urls import url

from .views import (
    PostCreate, PostList, PostUpdate,
    PostDelete, PostArchiveYear, PostArchiveMonth,
    PostDetail)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name='blog_post_archive_month'),

]

suorganizer/suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView


from blog import urls as blog_urls
from contact import urls as contact_urls
from organizer.urls import (
    startup as startup_urls,
    tag as tag_urls)
from user import urls as user_urls


admin.site.site_header = 'Startup Organizer Admin'
admin.site.site_title = 'Startup Organizer Site Admin'

urlpatterns = [
    
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^$', RedirectView.as_view(
            pattern_name='blog_post_list',
            permanent=False)),
    url(r'^user/', include(
                        user_urls,
                        app_name='user',
                        namespace='dj-auth')),
    
]

suorganizer/organizer/models.py
from datetime import date

from django.db import models
from django.core.urlresolvers import reverse



class TagManager(models.Manager):

    def get_by_natural_key(self,slug):
        return self.get(slug=slug)


class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True,
                            help_text='A label for URL config.')

    objects = TagManager()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_tag_detail',
                       args=(self.slug,))

    def get_update_url(self):
        return reverse('organizer_tag_update',
                        kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('organizer_tag_delete',
                        kwargs={'slug':self.slug})

    def published_posts(self):
        return self.blog_posts.filter(pub_date__lt=date.today())

    def natural_key(self):
        return (self.slug,)


class StartupManager(models.Manager):

    def get_by_natural_key(self,slug):
        return self.get(slug=slug)


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(max_length=31, unique=True,
                            help_text='A label for URL config.')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag, blank=True)

    objects = StartupManager()

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_startup_detail',
                      kwargs={'slug':self.slug})

    def get_newslink_create_url(self):
        return reverse(
            'organizer_newslink_create',
            kwargs={'startup_slug':self.slug})

    def get_update_url(self):
        return reverse('organizer_startup_update',
                        kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizer_startup_delete',
                        kwargs={'slug': self.slug})

    def natural_key(self):
        return (self.slug,)


class NewsLinkManager(models.Manager):

    def get_by_natural_key(self, startup_slug, slug):
        return self.get(startup__slug=startup_slug, slug=slug)


class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup)
    slug = models.SlugField(max_length=63)

    objects = NewsLinkManager()

    class Meta:
        verbose_name='news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        unique_together = ('slug','startup')

    def __str__(self):
        return "{}:{}".format(self.startup, self.title)

    def get_absolute_url(self):
        return self.startup.get_absolute_url()

    def get_update_url(self):
        return reverse('organizer_newslink_update',
                       kwargs={
                            'startup_slug':self.startup.slug,
                            'newslink_slug':self.slug})

    def get_delete_url(self):
        return reverse(
            'organizer_newslink_delete',
            kwargs={'startup_slug': self.startup.slug,
                    'newslink_slug': self.slug})

    def natural_key(self):
        return (self.startup.natural_key(),self.slug)
    natural_key.dependencies = ['organizer.startup']























    

suorganizer/organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import HiddenInput

from .models import Tag, NewsLink, Startup


class SlugCleanMixin:

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create"')
        return new_slug

class TagForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()
        

class NewsLinkForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'
        widgets = {'starup':HiddenInput()}

    # def save(self, **kwargs):
    #     instance = super().save(commit=False)
    #     instance.startup = self.data.get('startup')
    #     instance.save()
    #     self.save_m2m()
    #     return instance

    # def clean(self):
    #     cleaned_data = super().claen()
    #     slug = cleaned_data.get('slug')
    #     startup_obj = self.data.get('startup')
    #     exists = (
    #         NewsLink.objects.filter(
    #             slug__iexact=slug,
    #             startup=startup_obj,
    #         ).exists())
    #     if exists:
    #         raise ValidationError(
    #             "News articles with this slug"
    #             "and Startup already exists.")
    #     else:
    #         return cleaned_data


class StartupForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = '__all__'

suorganizer/organizer/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import (
    View, DetailView, CreateView, 
    DeleteView, ListView, DateDetailView)
from django.core.paginator import (
    EmptyPage, PageNotAnInteger, Paginator)
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import (
    login_required, 
    user_passes_test,
    permission_required)
from django.utils.decorators import method_decorator
from django.contrib.auth import PermissionDenied



from .models import Tag, Startup, NewsLink
from .forms import (
    TagForm, StartupForm, NewsLinkForm)
from .utils import (
    CreateView, ObjectUpdateMixin, ObjectDeleteMixin,
    PageLinksMixin,NewsLinkGetObjectMixin, StartupContextMixin)
from user.decorators import require_authenticated_permission, class_login_required

from core.utils import UpdateView


class TagList(PageLinksMixin, ListView):
    paginate_by = 5
    model = Tag


class StartupList(PageLinksMixin, ListView):
    model = Startup
    paginate_by = 5


class NewsLinkCreate(
                     NewsLinkGetObjectMixin,
                     StartupContextMixin,
                     CreateView):
    form_class = NewsLinkForm
    model = NewsLink

    def get_initial(self):
        startup_slug = self.kwargs.get(
            self.startup_slug_url_kwarg)
        self.startup = get_object_or_404(
            Startup, slug__iexact=startup_slug)
        initial = {
            self.startup_context_object_name:
                self.startup,
        }
        initial.update(self.initial)
        return initial


class StartupCreate(CreateView):
    form_class = StartupForm
    model = Startup
    template_name = 'organizer/startup_form.html'


def in_contrib_group(user):
    if user.groups.filter(name='contributors'):
        return True
    else:
        raise PermissionDenied


@require_authenticated_permission('organizer.add_tag')
class TagCreate(CreateView):
    form_class = TagForm
    model = Tag
    template_name = 'organizer/tag_form.html'

    


class NewsLinkUpdate(
        NewsLinkGetObjectMixin,
        StartupContextMixin,
        UpdateView):
    form_class = NewsLinkForm
    model = NewsLink
    slug_url_kwarg = 'newslink_slug'


@require_authenticated_permission('organizer.change_tag')
class TagUpdate(UpdateView):
    form_class = TagForm
    model = Tag


@require_authenticated_permission('organizer.change_startup')
class StartupUpdate(UpdateView):
    form_class = StartupForm
    model = Startup


class NewsLinkDelete(StartupContextMixin,DeleteView):
    model = NewsLink
    slug_url_kwarg = 'newslink_slug'


class TagDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy('organizer_tag_list')


class StartupDelete(DeleteView):
    model = Startup
    success_url = reverse_lazy('organizer_startup_list')
    


class TagPageList(View):
    paginate_by = 5
    template_name = 'organizer/tag_list.html'

    def get(self, request, page_number):
        tags = Tag.objects.all()
        paginator = Paginator(
            tags, self.paginate_by)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(
                paginator.num_pages)

        if page.has_previous():
            prev_url = reverse(
                'organizer_tag_page',
                args=(
                    page.previous_page_number(),
                ))
        else:
            prev_url = None
        if page.has_next():
            next_url = reverse(
                'organizer_tag_page',
                args=(
                    page.next_page_number(),
                ))
        else:
            next_url = None

        context = {
            'is_paginated':
                page.has_other_pages(),
            'next_page_url': next_url,
            'paginator':paginator,
            'previous_page_url': prev_url,
            'tag_list':page,
        }
        return render(
            request, self.template_name, context)


class TagDetail(DetailView):

    context_object_name = 'tag'
    model = Tag
    template_name = 'organizer/tag_detail.html'

class StartupDetail(DetailView):

    context_object_name = 'startup'
    model = Startup
    template_name = 'organizer/startup_detail.html'

suorganizer/organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

{% load staticfiles %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}">
{% endblock head %}

{% block content %}
    <div class="row">
        <section class="eight columns">
        {% block org_content %}
            This is default content!
        {% endblock org_content %}
        </section>

        <section class="desktop four columns">
            {% block create_button %}
                
            {% endblock create_button %}
        </section>
    </div>

    <div class="row">
        <div class="twelve columns">
            {% block content_footer %}
                {% if is_paginated %}
                    <ul class="pagination">
                        {% if previous_page_url %}
                            <li>
                                <a href="{{ previous_page_url }}">
                                    Previous
                                </a>
                            </li>
                        {% endif %}
                        {% if first_page_url %}
                            <li>
                                <a href="{{ first_page_url}}">
                                    First
                                </a>
                            </li>
                        {% endif %}
                        <li>
                            Page {{ page_obj.number }}
                            of {{ paginator.num_pages }}
                        </li>
                        {% if last_page_url %}
                            <li>
                                <a href="{{ last_page_url }}">
                                    Last
                                </a>
                            </li>
                        {% endif %}
                        {% if next_page_url %}
                            <li>
                                <a href="{{ next_page_url }}">
                                    Next
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            {% endblock content_footer %}
        </div>
    </div>

{% endblock content %}

suorganizer/organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Link News Article to Startup
{% endblock title %}

{% block content %}
    <div>
        <div>
            <form
                action="{{ startup.get_newslink_create_url }}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                    Link Article
                </button>
                
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/organizer/templates/organizer/startup_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete Startup
{% endblock title %}

{% block content %}
    <div>
        <div>
            <form 
                action="{{ startup.get_delete_url }}"
                method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete startup {{ startup.name }}?
                </p>
                <a href="{{ starup.get_delete_url }}">Cancel</a>
                <button type="submit">Delete Startup</button>
                
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - {{ startup.name|title }}
{% endblock title %}

{% block content %}
<article>
    <div class="row">
       <div class="offset-by-two eight column">
            <h2>{{ startup.name }}</h2>
            <ul class="inline">
                <li>
                    <a href="{{ startup.get_update_url }}"
                       class="button">
                        Edit Startup
                    </a>
                </li>
                <li>
                    <a href="{{ startup.get_delete_url }}"
                       class="button">
                        Delete Startup
                    </a>
                </li>
            </ul>
            <dl>
                <dt>Date Founded</dt>
                    <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
                <dt>Website</dt>
                    <dd>{{ startup.website|urlize }}</dd>
                <dt>Contact</dt>
                    <dd>{{ startup.contact }}</dd>
                <dt>Tag{{ startup.tags.count|pluralize }}</dt>
                {% for tag in startup.tags.all %}
                    <dd>
                        <a href="{{ tag.get_absolute_url }}">
                            {{ tag.name|title }}
                        </a>
                    </dd>
                {% endfor %}
            </dl>

            <p>{{ startup.description|linebreaks }}</p>
        </div> 
    </div>

    {% if startup.newslink_set.all 
       or startup.blog_posts.all 
       or perms.organizer.add_newslink %}
    <div class="row">
        {% if startup.blog_posts.all %}
            <section class="meta offset-by-two one-third column">
        {% else %}
            <section class="meta offset-by-two two-thirds column">
        {% endif %}
            <h3>Recent News</h3>
            <p>
                <a href="{{ startup.get_newslink_create_url }}"
                   class="button">
                    Add Article
                </a>
            </p>
            <ul>
                {% for newslink in startup.newslink_set.all %}
                    <li>
                        <a href="{{ newslink.link }}">
                            {{ newslink.title|title }}
                        </a>
                        <ul class="inline">
                            <li>
                                <a href="{{ newslink.get_update_url }}"
                                   class="button">
                                    Edit Link
                                </a>
                            </li>
                            <li>
                                <a href="{{ newslink.get_delete_url }}"
                                   class="button">
                                    Delete Link
                                </a>
                            </li>
                        </ul>

                    </li>
                {% endfor %}
                
            </ul>
        </section>
    </div>
    {% endif %}

    {% if perms.blog.view_future_post and startup.blog_posts.all %}
        <section class="meta offset-by-two one-third column">
    {% else %}
        <section class="meta offset-by-two two-thirds column">
            <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
            <ul>
                {% for post in startup.blog_posts.all %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title|title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
</article>
{% endblock content %}

suorganizer/organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Create Startup
{% endblock title %}


{% block content %}
    <div>
        <div>
            <form
                action="{% url 'organizer_startup_create' %}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                    Create Startup
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Update Startup
{% endblock title %}

{% block content %}
    <div>
        <div>
            <form
                action="{{ startup.get_update_url }}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                    Update Startup
                </button>
                
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Startups
{% endblock title %}

{% block create_button %}
    <a href="{% url 'organizer_startup_create' %}"
       class="button button-primary">
        Create new Startup
    </a>
{% endblock create_button %}

{% block org_content %}
    <h2>Startup List</h2>
    <div class="mobile">
        <a href="{% url 'organizer_startup_create' %}"
           class="button button-primary">
            Create New Startup
        </a>
    </div>
    <ul>
        {% for startup in startup_list %}
            <li>
                <a href="{{ startup.get_absolute_url }}">
                    {{ startup.name }}
                </a>
                <ul class="inline">
                    <li>
                        <a href="{{ startup.get_update_url }}"
                           class="button">
                            Edit Startup
                        </a>
                    </li>
                    <li>
                        <a href="{{ startup.get_delete_url }}"
                           class="button">
                            Delete Startup
                        </a>
                    </li>
                </ul>
            </li>
            
        {% empty %}
            <li><em>No Startups Available</em></li>
        {% endfor %}
    </ul>
{% endblock org_content %}

suorganizer/organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete Tag
{% endblock title %}

{% block content %}
    <div>
        <div>
            <form 
                action="{{ tag.get_delete_url }}"
                method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete tag {{ tag.name }}?
                </p>
                <a href="{{ tag.get_delete_url }}">Cancel</a>
                <button type="submit">Delete Tag</button>
                
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - {{ tag.name|title }}
{% endblock title %}

{% block content %}
    <ul>
        <li>
            {% if perms.organizer.change_tag or perms.organizer.delete_tag %}
                <a href="{{ tag.get_update_url }}">
                    Edit Tag
                </a>
            {% endif %}      
        </li>
        <li>
            <a href="{{ tag.get_delete_url }}">
                Delete Tag
            </a>
        </li>
    </ul>
    <h2>
        {{ tag.name|title }}
    </h2>
    {% if tag.startup_set.all %}
        <section>
            <h3>Startups{{ tag.startup_set.count|pluralize }}</h3>
            <p>
                Tag is associated with 
                {{ tag.startup_set.count }}
                startup{{ tag.startup_set.count|pluralize }}.
            </p>
            <ul>
                {% for startup in tag.startup_set.all %}
                    <li>
                        <a href="{{ startup.get_absolute_url }}">
                            {{ startup.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    {% if perms.blog.view_future_post %}
        <section>
            <h3>Blog Posts{{ tag.blog_posts.count|pluralize }}</h3>
            <ul>
                {% for post in tag.blog_posts.all %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title|title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>
        {% if not tag.startup_set.all and not tag.blog_posts.all %}
            <p>This tag is not related to any content</p>
        {% endif %}
    {% else %}
        <section>
            <h3>Blog Posts{{ tag.published_posts|pluralize }}</h3>
            <ul>
                {% for post in tag.published_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title|title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>
        {% if not tag.startup_set.all and not tag.published_posts %}
            <p>This tag is not related to any content</p>
        {% endif %}
    {% endif %}
    
{% endblock content %}

suorganizer/organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Create Tag
{% endblock title %}

{% block content %}
    <div>
        <div>
            <form action="{% url 'organizer_tag_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Tag</button>
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Update Tag
{% endblock title %}

{% block content %}
    <div>
        <div>
            <form
                action="{{ tag.get_update_url }}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">
                    Update Tag
                </button>
                
            </form>
        </div>
    </div>
{% endblock content %}

suorganizer/organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}


{% block title %}
    {{ block.super }} - Tag List
{% endblock title %}

{% block content %}
    <h2>Tag List</h2>
    <div>
        <a href="{% url 'organizer_tag_create' %}">
            Create New Tag
        </a>
    </div>
    <ul>
        {% for tag in tag_list %}
            <li>
                <a href="{{ tag.get_absolute_url }}">
                    {{ tag.name|title }}
                </a>
                <ul>
                    <li>
                        <a href="{{ tag.get_update_url }}">
                            Edit Tag
                        </a>
                    </li>
                    <li>
                        <a href="{{ tag.get_delete_url }}">
                            Delete Tag
                        </a>
                    </li>
                </ul>
            </li>
        {% empty %}
            <li><em>There are currently no Tags available.</em></li>
        {% endfor %}
    </ul>
{% endblock content %}